### ISSUE TITLE
ERC20Reserve rescue functionality

### ISSUE THREAD

**Issue by deckardkrug** [radicle-dev/radicle-drips-hub#82]
Currently it is not possible to rescue erc20 tokens from the reserve contract if some - other than the registered token - have been send to the contract by accident.

*If this is a concern I would be happy to push a pr.*

**Comment by CodeSandwich** [comment]
That's right, there's no such functionality. Do you think that it's a probable risk? The API is designed so you never explicitly `transfer` anything to the reserve, you ask the reserve to do that for you, so there's a lower chance to mess it up, at worst instead depositing X tokens A you'll deposit X tokens B, but that's a recoverable situation.

**Comment by deckardkrug** [comment]
I would say that it depends on the future use of the reserve. For the workstreams project it would be useful to have a more dynamic reserve that can hold multiple tokens at once as described [here](https://github.com/odyslam/radicle-workstreams/issues/3). This requires an implementation of a withdraw function where a user can withdraw multiple tokens. Another case would be if this contract is used to accrue interest. However, at the moment I can't give an example for a situation in which this would be needed.

I am a fan of [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) when it comes to smart contract development so let's keep it as it is for now.
