### ISSUE TITLE
Add scheduled drips

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-drips-hub#84]
It **may** be possible to support drips configurations with optional start and end time. The user would need to have balance covering at least all the drips with end times. Drips without end time probably should run for as long as balance allows.

Partially done in https://github.com/radicle-dev/radicle-drips-hub/issues/84, still to do:
- restore events emitted when setting drips
- add tests for the scheduled drips

**Comment by deckardkrug** [comment]
Is someone already working on this?

**Comment by CodeSandwich** [comment]
Currently it's just an idea, we need to take a closer look if it's even realistically doable. In short term we have more burning features to add, but this could be a valuable feature allowing more tools to be based on drips hub. One of the reasons why I've opened this issue is to signal a potential possibility and maybe get some feedback.

**Comment by deckardkrug** [comment]
@CodeSandwich okay, thank you.

As I imagine the implementation of this idea, it could be a check in `setDrips()` and two additional parameters. What I like about this idea is not necessary the end time but the start time. Using a start time, streams could be "scheduled".

**Comment by bordumb** [comment]
This would be a REALLY awesome feature.

I can even think of some IRL use cases:
* Time-limited fundraiser for an event: imagine you want to make a conference for 1,000 attendees. You could do a one-time fundraiser that starts at `day-0` and ends up `day-90`. Anyone who buys the NFT has a "ticket" for entry
* Time-limited charity auction: imagine you are raising money for some charity/cause. You could do a one-time fundraiser that starts at `day-0` and ends up `day-90`. Set limit to 10,000 NFTs. The NFT could become a raffle ticket, so maybe 1 out of the 10,000 will get some special prize and the rest of the funds go to a charity. **This would not be possible without a time limit**.

**Comment by CodeSandwich** [comment]
> Question: is this JUST for the one-off Drips? Or could it implemented for Community building, too?

It'd be for the drips, which is the feature where funds are flowing at a constant rate over a period of time. I think that we mean the same thing :wink:  It also covers one-offs because they can be easily emulated with this. You've invented some awesome use cases!

**Comment by bordumb** [comment]
FYI, I've continued my ideas on a new issue below
I think I was conflating **gives** and **drips** above
So the issue below focuses on **gives** within the context of fundraising 

https://github.com/radicle-dev/radicle-drips-hub/issues/89
