### ISSUE TITLE
Security & UX: Two transactions to set a drip is 1 too many

### ISSUE THREAD

**Issue by GriffGreen** [radicle-dev/radicle-drips-hub#87]
Use Permit for DAI instead of requiring infinite approve. better UX for a first time user and better security for everyone.

Don't be these guys: https://www.zdnet.com/article/multichain-token-hack-losses-reach-3-million-report/

**Comment by CodeSandwich** [comment]
Hi @GriffGreen,
Thanks for filing an issue! It seems like an issue with the transactions flow in the app, could you re-apply it in [**its repository**](https://github.com/radicle-dev/drips-app)? 

Regarding the issue itself, you should remember that Dai is a pre-ERC-712 token. The only permissions it understands are "unlimited" and "none". The only way to fine-tune its approvals is to NOT use permit but the old ERC-20 approvals, which generate the extra transactions which you mention in the title.

What we COULD do is accept on the contract level **2** permissions, one for approval and one for revocation. The contract would apply the first one, transferFrom as much as it needs and then immediately apply the second one.

**Comment by GriffGreen** [comment]
Oh my bad! You are right... their permit is not what i was dreaming!

It's a tough call.. UX vs Security... I like your suggestions but if it's not a huge win... probably no change is the way to go, changing the flow has a lot of extra work associated with it... sorry for being silly in the first place.

Thx for trying to appease me anyway tho!

**Comment by CodeSandwich** [comment]
Chill @GriffGreen, thanks for reacting to the suspicious app behavior you've found!
