### ISSUE TITLE
Add start/end date to One-Time Fundraiser

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/radicle-drips-hub#89]
## Proposal
Allow for a start/end date for One-Time Fundraisers (i.e. **gives**)

A start/end date essentially adds a time limit.

Could add to the end of the UI like so:
![image](https://user-images.githubusercontent.com/3743841/151985199-e8e2425c-8de7-4d78-be3e-000f326bdce2.png)

## Motivation
This would unlock a number of use cases, some with very IRL implications.

### Time-Limited Fundraiser/Charity

Similar to [GoFundMe](https://www.gofundme.com/)

Workflow:
* Start a charity drive with One-Time Fundraiser
* Name it "Product Launch Fundraiser"
* Set time limit for 3 months

> Consideration: in the case of fundraiser/charity, it may make sense to have a refund mechanism, such that if the goal of X amount is not met in Y time limit, 100% of funds are sent back to givers.

### IRL Events

Similar to [TicketMaster](https://www.ticketmaster.co.uk/), [EventBrite](https://www.eventbrite.co.uk/), [StubHub](https://www.stubhub.co.uk/), etc.

Workflow:
* Start a community with One-Time Fundraiser
* Name it "Eth Denver After Party - Feb 21"
* I have a start date of today
* I have an end date of Feb 21
* I set the minimum price to 50DAI (~$50 per "ticket")
* I set the NFT limit to 1,000 (= 1,000 tickets for entry)

> Consideration: this could be used for any kind of event; music, conference, art exhibit, etc.

**Comment by CodeSandwich** [comment]
I think that this use case is now covered with scheduled drips.
